import { StyleSheet, Platform, Dimensions } from 'react-native';

import { CoreConfig } from "@pru-rt-internal/rnmobile-app-core-framework";
const { colors } = CoreConfig;

const window = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    backgroundColor: colors.white,
    flex: 1,
    paddingTop: 8,
  },
  scrollviewContainer: {
    paddingLeft: 0,
    paddingRight: 20,
  },
  backIcnWrapper: {
    width: 50,
    height: 42,
  },
  backIcn: {
    width: 20,
    height: 20,
    marginTop: 12,
    marginLeft: 20,
  },
  modalStyle: {
    backgroundColor: colors.white,
    alignItems: 'center',
    height: 170,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.nevada,
    padding: 10,
  },
  modalLeftButton: {
    alignItems: 'center',
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginRight: 10,
    borderWidth: 0.5,
    borderColor: '#717171',
    borderRadius: 5,
  },
  modalRightButton: {
    alignItems: 'center',
    flex: 0.45,
    padding: 8,
    paddingTop: 15,
    paddingBottom: 15,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: '#717171',
    borderRadius: 5,
  },
  modalButtonLabel: {
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    fontSize: 13.3,
    lineHeight: 14.3,
    textAlign: 'center',
    paddingTop: 10,
  },
  link: {
    width: 60,
    height: 60,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    borderColor: '#ed1b2e',
    // backgroundColor: '#ed1b2e',
  },
  button: {
    alignItems: 'center',
    backgroundColor: '#ed1b2e',
    borderColor: '#ed1b2e',
    borderWidth: 1,
    borderRadius: 8,
    height: 40,
    margin: 15,
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 13,
    lineHeight: 15,
    color: '#ffffff',
    letterSpacing: 1.07,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
  },
  uploadImg: {
    width: 25,
    height: 25, 
    marginRight: 8,
  },
  uploadBtnContainer: {
    borderColor: '#a8a8a8',
    borderWidth: 1,
    flexDirection: 'row',
    maxWidth: 200,
    padding: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
    borderRadius: 12,
    marginBottom: 30,
    marginLeft: 20,
  },
  imageDetailContainer: {
    backgroundColor: '#ffffff',
    borderColor: '#a8a8a8',
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
    padding: 10,
    alignItems: 'center',
    flexWrap: 'wrap',
    borderRadius: 12,
    marginBottom: 30,
    marginLeft: 20,
    // marginRight: 20,
  },
  uploadBtn: {
    color: '#101010',
    borderRadius: 12,
    alignItems: 'center',
    flexWrap: 'wrap',
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
  },
  submitBtn: {
    width: '100%',
    backgroundColor: colors.crimson,
    height: 40,
    alignSelf: 'center',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
    marginTop: 62.3,
  },
  dropDownIcon: {
    position: 'absolute',
    right: 10,
  },
  btnText: {
    color: colors.white,
    marginTop: 2,
    fontSize: 14,
    lineHeight: 16,
    marginLeft: 20,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
  },
  thanksMsg: {
    color: colors.nevada,
    fontSize: 21.7,
    lineHeight: 25,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
    marginTop: 20,
    paddingLeft: 20,
  },
  thanksPara: {
    fontSize: 15.3,
    lineHeight: 18.3,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    paddingBottom: 16.7,
    marginTop: 13,
    borderBottomWidth: 1,
    borderColor: colors.silver,
    marginLeft: 20,
  },
  textStyle: {
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    textAlign: 'left',
    fontSize: 13.3,
    lineHeight: 18.3,
  },
  thanks: {
    marginBottom: 15,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
  },
  contactMsg: {
    color: colors.crimson,
  },
  feedback: {
    color: colors.nevada,
    fontSize: 15.3,
    lineHeight: 18.3,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
    marginTop: 30,
    marginBottom: 8,
  },

  attachedText: {
    color: colors.nevada,
    fontSize: 12.3,
    lineHeight: 15.3,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
    margin: 8,
    marginLeft: 4,
    width: window.width * 0.35,     
  },
  removeBtnContainer: {
    width: window.width * 0.3,
    justifyContent: 'center',
    borderColor: colors.crimson,
    borderWidth: 1,
    backgroundColor: '#ffffff',
    height: 40,
    borderRadius: 20,
  },
  removeBtnLabel: {
    textAlign: 'center',
    color: colors.crimson,
  },
  categoryContainer: {
    borderWidth: 1,
    borderColor: colors.silver,
    marginBottom: 10,
  },
  category: {
    height: 44.7,
    color: colors.nevada,
  },
  textInput: {
    color: colors.nevada,
    fontSize: 15.3,
    lineHeight: 18.3,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: colors.silver,
  },
  dropDownButton: {
    width:
      Platform.OS === 'ios'
        ? Dimensions.get('window').width - 50
        : Dimensions.get('window').width - 60,
    height: 31,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    fontSize: 13.3,
    lineHeight: 18.3,
    letterSpacing: 0,
    textAlign: 'left',
    paddingTop: 8,
    paddingLeft: 15,
    color: '#d2d2d2',
  },
  dropdownStyle: Platform.select({
    ios: {
      width: Dimensions.get('window').width - 50,
      backgroundColor: '#f2f2f2',
      marginTop: 10,
      marginLeft: -12,
    },
    android: {
      width: Dimensions.get('window').width - 65,
      backgroundColor: '#f2f2f2',
      marginTop: -15,
      marginLeft: -12,
    },
  }),
  dropdownTextStyle: {
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal' : 'pru-regular',
    fontSize: 13.3,
    lineHeight: 18.3,
    letterSpacing: 0,
    textAlign: 'left',
    paddingLeft: 15,
    backgroundColor: '#f2f2f2',
    color: colors.battleship_grey,
  },
  dropbox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderRadius: 6.7,
    borderStyle: 'solid',
    borderWidth: 0.3,
    borderColor: '#a8a8a8',
    width:
      Platform.OS === 'ios'
        ? Dimensions.get('window').width - 50
        : Dimensions.get('window').width - 60,
    marginLeft: 15,
    marginRight: 15,
    textAlign: 'center',
  },
  leftSpacing: {
    paddingLeft: 20,
  },
  feedbackCounter:{
    color: colors.silver,
    fontSize: 12.3,
    marginTop:-5,
    marginBottom: 5,
    fontFamily: Platform.OS === 'ios' ? 'PruSansNormal-Demi' : 'pru-bold',
    textAlign: 'right'
  }
});
