import { StyleSheet, Platform } from "react-native";

import {
  CoreConfig,
  colors,
} from "@pru-rt-internal/rnmobile-app-core-framework";

const { width, height } = CoreConfig;

export default StyleSheet.create({
  imageContainer: {
    flex: 1,
    alignItems: "center",
    width: width,
    height: height,
  },
  container: {
    flex: 1,
    alignItems: "center",
    width: "100%",
    height: "100%",
  },
  login: {
    color: colors.white,
    lineHeight: 14.3,
    letterSpacing: 1.01,
    fontSize: 12.7,
    fontFamily: Platform.OS == "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  loader: {
    width: width,
    height: height,
    justifyContent: "center",
    position: "absolute",
    left: 0,
    top: 0,
    opacity: 0.5,
    backgroundColor: "#404040",
    zIndex: 9,
  },
  topOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    alignItems: "center",
    paddingHorizontal: 20,
    position: "absolute",
    zIndex: 9,
    top: 0,
    width: "100%",
  },
  langContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "flex-start",
  },
  lang: {
    marginRight: 10,
    color: colors.white,
    lineHeight: 15.3,
    letterSpacing: 1.01,
    fontSize: 13.3,
    fontFamily: Platform.OS == "ios" ? "PruSansNormal-Demi" : "pru-bold",
  },
  babylonMidContent: {
    width: width,
    flexDirection: "column",
    padding: 10,
    marginTop: 40,
    position: "absolute",
    alignItems: "center",
    top: height * 0.45 - 10,
  },
  midContent: {
    width: width,
    flexDirection: "column",
    padding: 10,
    marginTop: 40,
    position: "absolute",
    alignItems: "center",
    top: height * 0.5 - 10,
  },
  brandImageContainer: {
    width: width,
    flexDirection: "column",
    marginBottom: 30,
    padding: 10,
    top: 60,
    position: "absolute",
    zIndex: 9,
  },
  babylonImage: {
    width: 120,
    height: 50,
    marginBottom: 10,
    // position: 'absolute',
    //bottom: Platform.select === 'ios' ? height * (1 / 5.5) - 13 : height * (1 / 5.5) - 5,
    //alignSelf: 'center',
  },
  brandImage: {
    width: 50,
    height: 45,
  },
  subtitle: {
    lineHeight: 26.7,
    fontSize: 18.3,
    color: colors.white,
    fontFamily: Platform.OS === "ios" ? "PruSansNormal" : "pru-regular",
    alignSelf: "center",
    textAlign: "center",
    marginTop: 10,
  },
  title: {
    lineHeight: 26.7,
    fontSize: 21.7,
    color: colors.white,
    fontFamily: Platform.OS == "ios" ? "PruSansNormal-Demi" : "pru-bold",
    alignSelf: "center",
    textAlign: "center",
  },
  getStart: {
    width: width - 40,
    padding: 10,
    borderRadius: 8,
    //  color: colors.white,
    backgroundColor: colors.red,
    justifyContent: "center",
    alignItems: "center",
    //fontSize: 18.6,
    //fontFamily: Platform.OS == "ios" ? "PruSansNormal-Demi" : "pru-bold",
    //textAlign: "center",
    alignSelf: "center",
  },
  backgroundImg: {
    width: "100%",
    height: "100%",
    position: "absolute",
    top: 0,
    left: 0,
  },
  or: {
    width: "80%",
    height: 12.3,
    marginTop: 10,
    marginBottom: 10,
    alignSelf: "center",
  },
  logoTopContainer: {
    marginBottom: 30,
    marginLeft: 30,
  },
  logoContainer: {
    display: "flex",
    justifyContent: "flex-start",
  },
  logo: {
    alignSelf: "flex-start",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  content: {
    position: "absolute",
    left: 0,
    top: 0,
    borderWidth: 3,
  },
  contentContainer: {
    height: height - 110,
  },
  hide: {
    opacity: 0,
  },
});
